%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

Camera1.fx: 1028.0
Camera1.fy: 1028.4
Camera1.cx: 609.03
Camera1.cy: 397.99

#cam_mat = np.array([[1028,0,609.03],[,0,1028.4,397.99],[,0,0,1]])
# k1, k2, p1, p2, k3, k4, k5, k6, s1, s2, s3, s4, Tx, Ty
#dist_coeffs = np.array([[-0.35952,0.080321,0.001794,-0.001439,0.025185]])


# distortion parameters
Camera1.k1: -0.35952
Camera1.k2: 0.080321
Camera1.p1: 0.001794
Camera1.p2: -0.001439

# Camera resolution
Camera.width: 1920
Camera.height: 1080

# Camera frames per second
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0

#--------------------------------------------------------------------------------------------
# Atlas Parameters
#--------------------------------------------------------------------------------------------
System.SaveAtlasToFile: "ORB_SLAM3_ROS2/maps/prev_atlas"
# System.LoadAtlasFromFile: "ORB_SLAM3_ROS2/maps/prev_atlas"
